Repository jenkinsci/mock-slave-plugin, pull requests merged in 2021-06, with the labels that each got.

#101 [JENKINS-65843] Update baseline to remove implicit dep on trilead-api
  pom.xml
Labels: dependencies

#102 Enable CD
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: chore

#103 Missing `repositories` and `pluginRepositories` sections in POM
  pom.xml
Labels: bug
